baseURL: "https://weshop.github.io/wenews"
paginate: 5
theme: PaperMod
publishDir: "docs"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
disableHugoGeneratorInject: true

summaryLength: 30

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  post: "/:filename/"
  page: "/:filename/"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: "Author"
  # author: ["Me", "You"] # multiple authors
  images: ["/favicon.png"]

  defaultTheme: auto # dark, light
  disableThemeToggle: false
  #defaultContentLanguage: en

  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"

  label:
    text: "WeNews"
    icon: "/favicon.ico"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: WeNews
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

languages:
  en:
    languageName: "en"
    weight: 1
    contentDir: content/en
    title: "WeNews"
    description: "At WeShop, you earn WeShares for shopping, sharing and engaging with other users."
    homeInfoParams:
      Title: "WeNews"
      Content: "
      Hey there 👋 !


      At WeShop, you earn WeShares for shopping, sharing and engaging with other users.


      Let's go 🚀
      "
    socialIcons:
      - name: instagram
        url: "https://www.instagram.com/weshopsocial"
      - name: twitter
        url: "https://twitter.com/WeShopSocial"
    menu:
      main:
        - identifier: search
          name: Search
          url: /search/
          weight: 15
        - identifier: faq
          name: FAQ
          url: /faq/
          weight: 25
